hostname ACC-SW1
!
vrf definition clab-mgmt
 !
 address-family ipv4
 exit-address-family
!
no ip domain lookup
ip domain name lab
ip cef
!
username admin privilege 15 secret 9 $9$ZUTImYsVRYnGBE$aJ8BJyJ.Hlr5dNrpNaqvS3JF0Ag/Y9SrHD1Dv1E28NA
!
vtp mode transparent
!
vlan 10
 name Servers
!
vlan 20
 name Users
!
vlan 30
 name Management
!
vlan 40
 name Guest
!
vlan 99
 name Native
!
spanning-tree mode rapid-pvst
spanning-tree extend system-id
!
interface Ethernet0/0
 description clab-mgmt
 no switchport
 vrf forwarding clab-mgmt
 ip address 172.31.34.22 255.255.255.0
!
interface Ethernet0/1
 description toward-DIST-SW-trunk
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 1
 switchport trunk allowed vlan 10,20,30,99
 switchport mode trunk
 no shutdown
!
interface Ethernet0/2
 description toward-PC1-access-vlan10
 switchport mode access
 switchport access vlan 1
 switchport port-security maximum 1
 switchport port-security mac-address 0000.dead.beef
 switchport port-security violation shutdown
 spanning-tree portfast
 no shutdown
!
interface Ethernet0/3
 description unused
 switchport mode access
 switchport access vlan 99
 shutdown
!
ip route vrf clab-mgmt 0.0.0.0 0.0.0.0 Ethernet0/0 172.31.34.1
ip ssh bulk-mode 131072
!
line con 0
 exec-timeout 0 0
 logging synchronous
line vty 0 4
 login local
 transport input ssh
!
end
