hostname CORE-R1
!
vrf definition clab-mgmt
 !
 address-family ipv4
 exit-address-family
!
no ip domain lookup
ip domain name lab
ip cef
!
username admin privilege 15 secret 9 $9$ZUTImYsVRYnGBE$aJ8BJyJ.Hlr5dNrpNaqvS3JF0Ag/Y9SrHD1Dv1E28NA
!
interface Loopback0
 ip address 10.255.0.2 255.255.255.255
 ip ospf 1 area 0
!
interface Ethernet0/0
 description clab-mgmt
 vrf forwarding clab-mgmt
 ip address 172.31.34.13 255.255.255.0
!
interface Ethernet0/1
 description toward-JUN-R1
 ip address 10.0.12.5 255.255.255.252
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 ANCjun2026
 ip ospf 1 area 0
 no shutdown
!
interface Ethernet0/2
 description toward-BR-R1
 ip address 10.0.13.1 255.255.255.252
 ip ospf authentication message-digest
 ip ospf message-digest-key 1 md5 wrongkey
 no shutdown
!
interface Ethernet0/3
 description toward-BR-R2
 ip address 10.0.14.1 255.255.255.252
 ip ospf hello-interval 20
 ip ospf 1 area 1
 no shutdown
!
router ospf 1
 router-id 10.255.0.2
 area 1 stub no-summary
 passive-interface Loopback0
 redistribute static subnets
!
ip route vrf clab-mgmt 0.0.0.0 0.0.0.0 Ethernet0/0 172.31.34.1
!
ip access-list standard 10
 permit 172.31.34.0 0.0.0.255
 permit 10.255.0.0 0.0.0.255
!
ntp master 3
ntp server 10.255.0.1
ip ssh bulk-mode 131072
!
line con 0
 exec-timeout 0 0
 logging synchronous
line vty 0 4
 access-class 10 in
 login local
 transport input ssh
!
end
