hostname DIST-SW
!
vrf definition clab-mgmt
 !
 address-family ipv4
 exit-address-family
!
no ip domain lookup
ip domain name lab
ip cef
ip routing
!
username admin privilege 15 secret 9 $9$ZUTImYsVRYnGBE$aJ8BJyJ.Hlr5dNrpNaqvS3JF0Ag/Y9SrHD1Dv1E28NA
!
vtp mode transparent
!
vlan 10
 name Servers
!
vlan 20
 name Users
!
!
vlan 40
 name Guest
!
vlan 99
 name Native
!
spanning-tree mode rapid-pvst
spanning-tree extend system-id
!
interface Loopback0
 ip address 10.255.0.5 255.255.255.255
 ip ospf 1 area 1
!
interface Ethernet0/0
 description clab-mgmt
 no switchport
 vrf forwarding clab-mgmt
 ip address 172.31.34.21 255.255.255.0
!
interface Ethernet0/1
 description toward-BR-R1-trunk
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 99
 switchport trunk allowed vlan 10,20,30,40,99
 switchport mode trunk
 no shutdown
!
interface Ethernet0/2
 description toward-BR-R2-trunk
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 99
 switchport trunk allowed vlan 10,20,30,40,99
 switchport mode trunk
 no shutdown
!
interface Ethernet0/3
 description toward-ACC-SW1-trunk
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 99
 switchport trunk allowed vlan 10,20,30,40,99
 switchport mode trunk
 no shutdown
!
interface Ethernet1/0
 description toward-ACC-SW2-trunk
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 99
 switchport trunk allowed vlan 10,20,30,40,99
 switchport mode trunk
 no shutdown
!
interface Vlan10
 description SVI-Servers
 ip address 10.10.10.5 255.255.255.0
 ip ospf 1 area 1
 no shutdown
!
interface Vlan20
 description SVI-Users
 ip address 10.10.20.2 255.255.255.0
 ip ospf 1 area 1
 shutdown
!
interface Vlan30
 description SVI-Management
 ip address 10.10.30.2 255.255.255.0
 ip ospf 1 area 1
 no shutdown
!
interface Vlan40
 description SVI-Guest
 ip address 10.10.40.2 255.255.255.0
 ip ospf 1 area 1
 no shutdown
!
router ospf 1
 router-id 10.255.0.5
 passive-interface Loopback0
!
ip dhcp excluded-address 10.10.10.1 10.10.10.9
ip dhcp excluded-address 10.10.20.1 10.10.20.9
!
ip dhcp pool VLAN10
 network 10.10.10.0 255.255.255.0
 dns-server 8.8.8.8
 lease 0 0 30
!
ip dhcp pool VLAN20
 network 10.10.20.0 255.255.255.0
 default-router 10.10.20.1
 dns-server 8.8.8.8
 lease 0 0 30
!
ip route vrf clab-mgmt 0.0.0.0 0.0.0.0 Ethernet0/0 172.31.34.1
!
ntp server 10.255.0.2
ip ssh bulk-mode 131072
!
line con 0
 exec-timeout 0 0
 logging synchronous
line vty 0 4
 login local
 transport input ssh
!
end
