hostname ISP-R
!
vrf definition clab-mgmt
 !
 address-family ipv4
 exit-address-family
!
no ip domain lookup
ip domain name lab
ip cef
!
username admin privilege 15 secret 9 $9$ZUTImYsVRYnGBE$aJ8BJyJ.Hlr5dNrpNaqvS3JF0Ag/Y9SrHD1Dv1E28NA
!
interface Loopback0
 ip address 1.1.1.1 255.255.255.255
!
interface Ethernet0/0
 description clab-mgmt
 vrf forwarding clab-mgmt
 ip address 172.31.34.11 255.255.255.0
!
interface Ethernet0/1
 description toward-JUN-R1
 ip address 203.0.113.1 255.255.255.252
 no shutdown
!
router bgp 65000
 bgp router-id 1.1.1.1
 bgp log-neighbor-changes
 neighbor 203.0.113.2 remote-as 65100
 neighbor 203.0.113.2 description JUN-R1
 !
 address-family ipv4
  network 0.0.0.0
  network 1.1.1.1 mask 255.255.255.255
  neighbor 203.0.113.2 activate
  neighbor 203.0.113.2 send-community both
  neighbor 203.0.113.2 route-map TO-JUN-R1 out
 exit-address-family
!
ip route 0.0.0.0 0.0.0.0 Null0
ip route vrf clab-mgmt 0.0.0.0 0.0.0.0 Ethernet0/0 172.31.34.1
!
route-map TO-JUN-R1 permit 10
 set community 65000:100
!
ntp master 2
ip ssh bulk-mode 131072
!
line con 0
 exec-timeout 0 0
 logging synchronous
line vty 0 4
 login local
 transport input ssh
!
end
